var Icon = {
    Glass               : "\uf000",
    Music               : "\uf001",
    Search              : "\uf002",
    Envelope            : "\uf003",
    Heart               : "\uf004",
    Star                : "\uf005",
    StarEmpty           : "\uf006",
    User                : "\uf007",
    Film                : "\uf008",
    ThLarge             : "\uf009",
    Th                  : "\uf00a",
    ThList              : "\uf00b",
    Ok                  : "\uf00c",
    Remove              : "\uf00d",
    ZoomIn              : "\uf00e",
    ZoomOut             : "\uf010",
    Off                 : "\uf011",
    Signal              : "\uf012",
    Cog                 : "\uf013",
    Trash               : "\uf014",
    Home                : "\uf015",
    File                : "\uf016",
    Time                : "\uf017",
    Road                : "\uf018",
    DownloadAlt         : "\uf019",
    Download            : "\uf01a",
    Upload              : "\uf01b",
    Inbox               : "\uf01c",
    PlayCircle          : "\uf01d",
    Repeat              : "\uf01e",
    Refresh             : "\uf021",
    ListAlt             : "\uf022",
    Lock                : "\uf023",
    Flag                : "\uf024",
    Headphones          : "\uf025",
    VolumeOff           : "\uf026",
    VolumeDown          : "\uf027",
    VolumeUp            : "\uf028",
    Qrcode              : "\uf029",
    Barcode             : "\uf02a",
    Tag                 : "\uf02b",
    Tags                : "\uf02c",
    Book                : "\uf02d",
    Bookmark            : "\uf02e",
    Print               : "\uf02f",
    Camera              : "\uf030",
    Font                : "\uf031",
    Bold                : "\uf032",
    Italic              : "\uf033",
    TextHeight          : "\uf034",
    TextWidth           : "\uf035",
    AlignLeft           : "\uf036",
    AlignCenter         : "\uf037",
    AlignRight          : "\uf038",
    AlignJustify        : "\uf039",
    List                : "\uf03a",
    IndentLeft          : "\uf03b",
    IndentRight         : "\uf03c",
    FacetimeVideo       : "\uf03d",
    Picture             : "\uf03e",
    Pencil              : "\uf040",
    MapMarker           : "\uf041",
    Adjust              : "\uf042",
    Tint                : "\uf043",
    Edit                : "\uf044",
    Share               : "\uf045",
    Check               : "\uf046",
    Move                : "\uf047",
    StepBackward        : "\uf048",
    StepForward         : "\uf049",
    Backward            : "\uf04a",
    Play                : "\uf04b",
    Pause               : "\uf04c",
    Stop                : "\uf04d",
    Forward             : "\uf04e",
    FastForward         : "\uf050",
    StepForward         : "\uf051",
    Eject               : "\uf052",
    ChevronLeft         : "\uf053",
    ChevronRight        : "\uf054",
    PlusSign            : "\uf055",
    MinusSign           : "\uf056",
    RemoveSign          : "\uf057",
    OkSign              : "\uf058",
    QuestionSign        : "\uf059",
    InfoSign            : "\uf05a",
    Screenshot          : "\uf05b",
    RemoveCircle        : "\uf05c",
    OkCircle            : "\uf05d",
    BanCircle           : "\uf05e",
    ArrowLeft           : "\uf060",
    ArrowRight          : "\uf061",
    ArrowUp             : "\uf062",
    ArrowDown           : "\uf063",
    ShareAlt            : "\uf064",
    ResizeFull          : "\uf065",
    ResizeSmall         : "\uf066",
    Plus                : "\uf067",
    Minus               : "\uf068",
    Asterish            : "\uf069",
    ExclamationSign     : "\uf06a",
    Gift                : "\uf06b",
    Leave               : "\uf06c",
    Fire                : "\uf06d",
    EyeOpen             : "\uf06e",
    EyeClose            : "\uf070",
    WarningSign         : "\uf071",
    Plane               : "\uf072",
    Calendar            : "\uf073",
    Random              : "\uf074",
    Comment             : "\uf075",
    Magnet              : "\uf076",
    ChevronUp           : "\uf077",
    ChevronDown         : "\uf078",
    Retweet             : "\uf079",
    ShoppingCart        : "\uf07a",
    FolderClose         : "\uf07b",
    FolderOpen          : "\uf07c",
    ResizeVertical      : "\uf07d",
    ResizeHorizontal    : "\uf07e",
    BarChart            : "\uf080",
    TwitterSign         : "\uf081",
    FacebookSign        : "\uf082",
    CameraRetro         : "\uf083",
    Key                 : "\uf084",
    Cogs                : "\uf085",
    Comments            : "\uf086",
    ThumbsUp            : "\uf087",
    ThumbsDown          : "\uf088",
    StarHalf            : "\uf089",
    HeartEmpty          : "\uf08a",
    Signout             : "\uf08b",
    LinkedinSign        : "\uf08c",
    Pushpin             : "\uf08d",
    ExternalLink        : "\uf08e",
    Signin              : "\uf090",
    Trophy              : "\uf091",
    GithubSign          : "\uf092",
    UploadAlt           : "\uf093",
    Lemon               : "\uf094",
    Phone               : "\uf095",
    CheckEmpty          : "\uf096",
    BookmarkEmpty       : "\uf097",
    PhoneSign           : "\uf098",
    Twitter             : "\uf099",
    Facebook            : "\uf09a",
    Github              : "\uf09b",
    Unlock              : "\uf09c",
    CreditCard          : "\uf09d",
    Rss                 : "\uf09e",
    Hdd                 : "\uf0a0",
    Bullhorn            : "\uf0a1",
    Bell                : "\uf0a2",
    Certificate         : "\uf0a3",
    HandRight           : "\uf0a4",
    HandLeft            : "\uf0a5",
    HandUp              : "\uf0a6",
    HandDown            : "\uf0a7",
    CircleArrowLeft     : "\uf0a8",
    CircleArrowRight    : "\uf0a9",
    CircleArrowUp       : "\uf0aa",
    CircleArrowDown     : "\uf0ab",
    Globe               : "\uf0ac",
    Wrench              : "\uf0ad",
    Tasks               : "\uf0ae",
    Filter              : "\uf0b0",
    Briefcase           : "\uf0b1",
    Fullscreen          : "\uf0b2",
    Group               : "\uf0c0",
    Link                : "\uf0c1",
    Cloud               : "\uf0c2",
    Beaker              : "\uf0c3",
    Cut                 : "\uf0c4",
    Copy                : "\uf0c5",
    PaperClip           : "\uf0c6",
    Save                : "\uf0c7",
    SignBlank           : "\uf0c8",
    Reorder             : "\uf0c9",
    ListUl              : "\uf0ca",
    ListOl              : "\uf0cb",
    Strikethrough       : "\uf0cc",
    Underline           : "\uf0cd",
    Table               : "\uf0ce",
    Magic               : "\uf0d0",
    Truck               : "\uf0d1",
    Pinterest           : "\uf0d2",
    PinterestSign       : "\uf0d3",
    GooglePlusSign      : "\uf0d4",
    GooglePlus          : "\uf0d5",
    Money               : "\uf0d6",
    CaretDown           : "\uf0d7",
    CaretUp             : "\uf0d8",
    CaretLeft           : "\uf0d9",
    CaretRight          : "\uf0da",
    Columns             : "\uf0db",
    Sort                : "\uf0dc",
    SortDown            : "\uf0dd",
    SortUp              : "\uf0de",
    EnvelopeAlt         : "\uf0e0",
    Linkedin            : "\uf0e1",
    Undo                : "\uf0e2",
    Legal               : "\uf0e3",
    Dashboard           : "\uf0e4",
    CommentAlt          : "\uf0e5",
    CommentsAlt         : "\uf0e6",
    Bolt                : "\uf0e7",
    Sitemap             : "\uf0e8",
    Unbrella            : "\uf0e9",
    Paste               : "\uf0ea",
    UserMd              : "\uf200",
    Circle              : "\uf111",
    EyeSlash            : "\uf070",
};
var CharUTF8 = [
    "\uf000",
    "\uf001",
    "\uf002",
    "\uf003",
    "\uf004",
    "\uf005",
    "\uf006",
    "\uf007",
    "\uf008",
    "\uf009",
    "\uf00a",
    "\uf00b",
    "\uf00c",
    "\uf00d",
    "\uf00e",
    "\uf010",
    "\uf011",
    "\uf012",
    "\uf013",
    "\uf014",
    "\uf015",
    "\uf016",
    "\uf017",
    "\uf018",
    "\uf019",
    "\uf01a",
    "\uf01b",
    "\uf01c",
    "\uf01d",
    "\uf01e",
    "\uf021",
    "\uf022",
    "\uf023",
    "\uf024",
    "\uf025",
    "\uf026",
    "\uf027",
    "\uf028",
    "\uf029",
    "\uf02a",
    "\uf02b",
    "\uf02c",
    "\uf02d",
    "\uf02e",
    "\uf02f",
    "\uf030",
    "\uf031",
    "\uf032",
    "\uf033",
    "\uf034",
    "\uf035",
    "\uf036",
    "\uf037",
    "\uf038",
    "\uf039",
    "\uf03a",
    "\uf03b",
    "\uf03c",
    "\uf03d",
    "\uf03e",
    "\uf040",
    "\uf041",
    "\uf042",
    "\uf043",
    "\uf044",
    "\uf045",
    "\uf046",
    "\uf047",
    "\uf048",
    "\uf049",
    "\uf04a",
    "\uf04b",
    "\uf04c",
    "\uf04d",
    "\uf04e",
    "\uf050",
    "\uf051",
    "\uf052",
    "\uf053",
    "\uf054",
    "\uf055",
    "\uf056",
    "\uf057",
    "\uf058",
    "\uf059",
    "\uf05a",
    "\uf05b",
    "\uf05c",
    "\uf05d",
    "\uf05e",
    "\uf060",
    "\uf061",
    "\uf062",
    "\uf063",
    "\uf064",
    "\uf065",
    "\uf066",
    "\uf067",
    "\uf068",
    "\uf069",
    "\uf06a",
    "\uf06b",
    "\uf06c",
    "\uf06d",
    "\uf06e",
    "\uf070",
    "\uf071",
    "\uf072",
    "\uf073",
    "\uf074",
    "\uf075",
    "\uf076",
    "\uf077",
    "\uf078",
    "\uf079",
    "\uf07a",
    "\uf07b",
    "\uf07c",
    "\uf07d",
    "\uf07e",
    "\uf080",
    "\uf081",
    "\uf082",
    "\uf083",
    "\uf084",
    "\uf085",
    "\uf086",
    "\uf087",
    "\uf088",
    "\uf089",
    "\uf08a",
    "\uf08b",
    "\uf08c",
    "\uf08d",
    "\uf08e",
    "\uf090",
    "\uf091",
    "\uf092",
    "\uf093",
    "\uf094",
    "\uf095",
    "\uf096",
    "\uf097",
    "\uf098",
    "\uf099",
    "\uf09a",
    "\uf09b",
    "\uf09c",
    "\uf09d",
    "\uf09e",
    "\uf0a0",
    "\uf0a1",
    "\uf0a2",
    "\uf0a3",
    "\uf0a4",
    "\uf0a5",
    "\uf0a6",
    "\uf0a7",
    "\uf0a8",
    "\uf0a9",
    "\uf0aa",
    "\uf0ab",
    "\uf0ac",
    "\uf0ad",
    "\uf0ae",
    "\uf0b0",
    "\uf0b1",
    "\uf0b2",
    "\uf0c0",
    "\uf0c1",
    "\uf0c2",
    "\uf0c3",
    "\uf0c4",
    "\uf0c5",
    "\uf0c6",
    "\uf0c7",
    "\uf0c8",
    "\uf0c9",
    "\uf0ca",
    "\uf0cb",
    "\uf0cc",
    "\uf0cd",
    "\uf0ce",
    "\uf0d0",
    "\uf0d1",
    "\uf0d2",
    "\uf0d3",
    "\uf0d4",
    "\uf0d5",
    "\uf0d6",
    "\uf0d7",
    "\uf0d8",
    "\uf0d9",
    "\uf0da",
    "\uf0db",
    "\uf0dc",
    "\uf0dd",
    "\uf0de",
    "\uf0e0",
    "\uf0e1",
    "\uf0e2",
    "\uf0e3",
    "\uf0e4",
    "\uf0e5",
    "\uf0e6",
    "\uf0e7",
    "\uf0e8",
    "\uf0e9",
    "\uf0ea",
    "\uf200",
    "\uf111",
    "\uf070",
];
